import Head from 'next/head';
import ScrollingColorBackground from 'react-scrolling-color-background';
import styles from '../styles/Home.module.css';

const darkPurpleRgb = 'rgb(101, 45, 172)';
const ceriseRgb = 'rgb(217, 38, 136)';
const pumpkinRgb = 'rgb(255, 102, 22)';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ScrollingColorBackground
          selector=".js-color-stop[data-background-color]"
          colorDataAttribute="data-background-color"
          initialRgb="rgb(0, 0, 0)"
        />
        <section
          className="js-color-stop"
          data-background-color={darkPurpleRgb}
          style={{ height: '100vh' }}
        />
        <section
          className="js-color-stop"
          data-background-color={ceriseRgb}
          style={{ height: '100vh' }}
        />
      </main>
    </div>
  );
}
